apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  namespace: db
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
        - name: oracle-db
          image: container-registry-saopaulo.oracle.com/database/free:23.3.0.0
          ports:
          - containerPort: 1521
          env:
          - name: ORACLE_PWD
            value: TestM123
          - name: ORACLE_SID
            value: FREE
          - name: ORACLE_PDB
            value: FREEPDB1
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  namespace: db
spec:
  selector:
    app: oracle-db
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1521
    targetPort: 1521
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: study
type: Opaque
data:
  user: U1lTVEVN
  password: VGVzdE0xMjM=