apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-role
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "services", "secrets", "configmaps"]
  verbs: ["get", "watch", "list"]