logging:
  level:
    org:
      springframework:
        web: trace
    root: trace
spring:
  application:
    name: spring-kubernetes
  cloud:
    config:
      enabled: false
    kubernetes:
      config:
        enabled: true
        name: spring-kubernetes
        sources:
         - name: ${KUBE_CONFIGMAP}
server:
  servlet:
    context-path: ${CONTEXT-PATH}