spring:
  application:
    name: graalvm-example
  cloud:
    kubernetes:
      config:
        name: ${spring.application.name}
        namespace: default
        enabled: true
      reload:
        strategy: refresh
        enabled: true