spring:
  cloud:
    config:
      enabled: false
    kubernetes:
      config:
        enabled: true
        name: ${KUBE_CONFIGMAP}
        paths:
        - /etc/config/application.yml
  main:
    allow-bean-definition-overriding: true