spring:
  application:
    name: toolkit-sample
  datasource:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/toolkit
    username: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 30000
  jpa:
    open-in-view: false
  profiles:
    active: kubernetes
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    context-path: /toolkit-sample
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus