kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-jpa
  namespace: study
data:
  application.yml: |-
    spring:
      application:
        name: cloud-jpa
      datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USER}
      jpa:
        generate-ddl: true
        hibernate:
          ddl-auto: update
        show-sql: true
      profiles:
        active: kubernetes
    springdoc:
      swagger-ui:
        path: /swagger-ui.html
    server:
      servlet:
        context-path: /cloud-jpa
    management:
      endpoint:
        health:
          probes:
            enabled: true