apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: graalvm-example
  name: graalvm-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graalvm-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: graalvm-example
    spec:
      containers:
      - image: marsdeimos/graalvm-example:2.2
        name: graalvm-example
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: 10m
            memory: 50Mi
        env:
        - name: MESSAGE
          value: "Hello world, testing graalvm with spring cloud"

status: {}
