apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graalvm-connector
  namespace: study
  labels:
    app: graalvm-connector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graalvm-connector
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}