apiVersion: v1
kind: Service
metadata:
  name: graalvm-connector-service
  namespace: study
  labels:
    app: graalvm-connector
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: graalvm-connector
